Repository khulnasoft/ThreatMatrix, pull requests merged in 2024-07, with the labels that each got.

#16 update
  .flake8
  api_app/analyzers_manager/admin.py
  api_app/analyzers_manager/file_analyzers/doc_info.py
  api_app/analyzers_manager/migrations/0075_adjust_greynoise.py
  api_app/analyzers_manager/observable_analyzers/intelx.py
  api_app/analyzers_manager/observable_analyzers/spyse.py
  api_app/analyzers_manager/observable_analyzers/urlscan.py
  api_app/connectors_manager/admin.py
  api_app/connectors_manager/connectors/email_sender.py
  api_app/connectors_manager/connectors/opencti.py
  api_app/connectors_manager/connectors/slack.py
  api_app/ingestors_manager/admin.py
  api_app/interfaces.py
  api_app/investigations_manager/queryset.py
  api_app/pivots_manager/admin.py
  api_app/queryset.py
  api_app/serializers/job.py
  api_app/serializers/plugin.py
  api_app/visualizers_manager/admin.py
  api_app/visualizers_manager/visualizers/dns.py
  api_app/visualizers_manager/visualizers/domain_reputation_services.py
  api_app/visualizers_manager/visualizers/ip_reputation_services.py
  authentication/migrations/0005_create_profiles.py
  authentication/migrations/0006_alter_userprofile_company_name_and_more.py
Labels: enhancement, formatting, Review effort [1-5]: 3

#31 Develop
  frontend/package-lock.json
  frontend/package.json
  requirements/test-requirements.txt
Labels: dependencies, Review effort [1-5]: 2

#33 Bump elasticsearch-dsl from 8.13.0 to 8.14.0 in /requirements
  requirements/project-requirements.txt
Labels: dependencies, Review effort [1-5]: 1, Bug fix

#50 Develop
  frontend/package-lock.json
  frontend/package.json
  requirements/docs-requirements.txt
  requirements/project-requirements.txt
  requirements/test-requirements.txt
Labels: enhancement, dependencies, Review effort [1-5]: 2
